name: Main
on: push
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get short commit SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short $GITHUB_SHA)"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        run: |
          docker build . --tag ghcr.io/uikola/app:${{ steps.vars.outputs.sha_short }}
          docker push ghcr.io/uikola/app:${{ steps.vars.outputs.sha_short }}
