name: Main
on: push
jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t app -f Dockerfile .
      - name: Run
        run: docker run -p 8000:8000 app:latest

